"""empty message

Revision ID: 6cbffbfe9a52
Revises: ca9aa09d4bf4
Create Date: 2026-04-02 14:11:00.369080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cbffbfe9a52'
down_revision = 'ca9aa09d4bf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('company_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('company_logo', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('company_address', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('company_city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('company_phone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('company_email', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('company_gst', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('company_alternate_phone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('company_bank_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('company_bank_account', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('company_bank_ifsc', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('company_bank_branch', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('company_upi_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('payment_card_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('payment_card_holder', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('payment_upi_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('payment_transaction_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('payment_bank_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('payment_cheque_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('cash_received', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('created_by_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.drop_column('created_by_name')
        batch_op.drop_column('cash_received')
        batch_op.drop_column('payment_cheque_number')
        batch_op.drop_column('payment_bank_name')
        batch_op.drop_column('payment_transaction_id')
        batch_op.drop_column('payment_upi_id')
        batch_op.drop_column('payment_card_holder')
        batch_op.drop_column('payment_card_number')
        batch_op.drop_column('company_upi_id')
        batch_op.drop_column('company_bank_branch')
        batch_op.drop_column('company_bank_ifsc')
        batch_op.drop_column('company_bank_account')
        batch_op.drop_column('company_bank_name')
        batch_op.drop_column('company_alternate_phone')
        batch_op.drop_column('company_gst')
        batch_op.drop_column('company_email')
        batch_op.drop_column('company_phone')
        batch_op.drop_column('company_city')
        batch_op.drop_column('company_address')
        batch_op.drop_column('company_logo')
        batch_op.drop_column('company_name')
        batch_op.drop_column('company_id')

    # ### end Alembic commands ###
