"""empty message

Revision ID: ca9aa09d4bf4
Revises: 027e77548666
Create Date: 2026-04-01 22:14:49.679757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca9aa09d4bf4'
down_revision = '027e77548666'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('base_template', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_types', schema=None) as batch_op:
        batch_op.drop_column('base_template')

    # ### end Alembic commands ###
